// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXOMIqDJ2Du659Q3pqhnPNZyn7bP5_i_A',
    appId: '1:1004085423869:web:2426ce19fa4982e1e5d894',
    messagingSenderId: '1004085423869',
    projectId: 'sprout-c5452',
    authDomain: 'sprout-c5452.firebaseapp.com',
    storageBucket: 'sprout-c5452.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbImZmzwVRXEZLvIi7bJxCF50uukgVTMc',
    appId: '1:1004085423869:android:e84ed73c782a5056e5d894',
    messagingSenderId: '1004085423869',
    projectId: 'sprout-c5452',
    storageBucket: 'sprout-c5452.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXOMIqDJ2Du659Q3pqhnPNZyn7bP5_i_A',
    appId: '1:1004085423869:web:1193555a210a59b4e5d894',
    messagingSenderId: '1004085423869',
    projectId: 'sprout-c5452',
    authDomain: 'sprout-c5452.firebaseapp.com',
    storageBucket: 'sprout-c5452.firebasestorage.app',
  );
}
